can_ports: ["can4", "can5"]
max_current_A: 2
has_endstop: true
calibration:
    endstop_search_torques_Nm: [-0.22, -0.22, -0.22]
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd: [0.08, 0.08, 0.04]
position_control_gains:
    kp: [6, 6, 6]
    kd: [0.03, 0.03, 0.03]

# Set zero-position according to URDF (finger pointing straight down).
home_offset_rad:
    - 1.049
    - 1.297
    - 2.782
initial_position_rad: [0, -.8, -1.5]



joint_lower_limits: [-1.6, -1.4, -3.1]
joint_upper_limits: [1.6, 4.5, 3.1]

