can_ports: ["can2", "can3"]
max_current_A: 2
has_endstop: false
move_to_position_tolerance_rad: 0.05
calibration:
    endstop_search_torques_Nm: [0.22, 0.22, -0.18]
    move_steps: 500
safety_kd: [0.08, 0.08, 0.04]
position_control_gains:
    kp: [7, 7, 6.5]
    kd: [0.01, 0.015, 0.02]
hard_position_limits_lower: [-2.0, -1.4, -3.2]
hard_position_limits_upper: [1.6, 1.8, 3.2]

home_offset_rad: [-0.642, -0.247, -0.616]
initial_position_rad: [0, 0, 0]

hard_position_limits_lower: [-1.6, -1.4, -3.1]
hard_position_limits_upper: [1.6, 4.5, 3.1]

