# can6: MPI board
# can7: TI Launchpad
can_ports: ["can6"]

max_current_A: 2
has_endstop: true
calibration:
    endstop_search_torques_Nm: [-0.22]
    position_tolerance_rad: 0.05
    move_timeout: 2000
safety_kd: [0.08]
position_control_gains:
    kp: [3]
    kd: [0.03]

# Offset between encoder index and zero-position (in radian).
# Set this such that the zero position is in the center between left and
# right end stop.
home_offset_rad: [2.241742]
initial_position_rad: [0.0]

joint_lower_limits: [-3.2]
joint_upper_limits: [3.2]

