# can6: MPI board
# can7: TI Launchpad
can_ports: ["can6"]

max_current_A: 2
has_endstop: true
move_to_position_tolerance_rad: 0.05
calibration:
    endstop_search_torques_Nm: [-0.22, -0.22]
    move_steps: 500
safety_kd: [0.08, 0.08]
position_control_gains:
    kp: [3, 3]
    kd: [0.03, 0.03]

hard_position_limits_lower: [-.inf, -.inf]
hard_position_limits_upper: [.inf, .inf]

# Offset between encoder index and zero-position (in radian).
# Set this such that the zero position is in the center between left and
# right end stop.
home_offset_rad: [2.256, 2.2209]
initial_position_rad: [0, 0]
