# Build the package and run tests, using the latest trifinger_user Apptainer
# image.
# The Apptainer image has a full ROBOT_FINGERS workspace installed, so all
# dependencies are there and only the checked package needs to be build, not the
# whole workspace.
#
# Note: The Apptainer image only gets automatically rebuild, if something in the
# image definition changes, not when other packages are changed.  So to avoid
# that the workspace in the container gets outdated, manual builds need to be
# triggered regularly.

name: Build and Test

on: pull_request

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Apptainer
        uses: open-dynamic-robot-initiative/trifinger-build-action/setup_apptainer@v2

      - name: Build
        uses: open-dynamic-robot-initiative/trifinger-build-action/build@v2

      - name: Tests
        uses: open-dynamic-robot-initiative/trifinger-build-action/run_tests@v2
